"""
Live league integration with TheSportsDB.

Our club competes in the Italian Volleyball League (SuperLega).
We pull real fixtures, scores and team data from TheSportsDB's free
public API and surface them to the coach portal.

The free key (3) supports:
    eventsround.php   — events for a given league round / season
    eventslast.php    — last event for a team
    search_all_teams  — list teams in a league
    lookupleague.php  — league metadata
"""
from __future__ import annotations

import datetime as _dt
import hashlib
import json
import time
from pathlib import Path

import requests
from django.conf import settings
from django.core.cache import cache


_BASE = "https://www.thesportsdb.com/api/v1/json"
_DEFAULT_TTL = 60 * 60 * 6   # 6 hours — caches stay warm for the whole demo
_THROTTLE_SECONDS = 0.25      # spread requests so we don't trigger the 429 limit
_SNAPSHOT_PATH = Path(__file__).resolve().parent / "league_snapshot.json"
_last_request_at = 0.0


def _api_url(path: str) -> str:
    return f"{_BASE}/{settings.LEAGUE_API_KEY}/{path}"


def _cache_key(path: str, params: dict | None) -> str:
    raw = f"{path}|{sorted((params or {}).items())}"
    digest = hashlib.md5(raw.encode("utf-8")).hexdigest()
    return f"league:{digest}"


def _throttle():
    global _last_request_at
    elapsed = time.monotonic() - _last_request_at
    if elapsed < _THROTTLE_SECONDS:
        time.sleep(_THROTTLE_SECONDS - elapsed)
    _last_request_at = time.monotonic()


def _get_json(path: str, params: dict | None = None, ttl: int = _DEFAULT_TTL) -> dict:
    cache_key = _cache_key(path, params)
    hit = cache.get(cache_key)
    if hit is not None:
        return hit

    _throttle()
    data: dict = {}
    try:
        resp = requests.get(
            _api_url(path),
            params=params or {},
            timeout=settings.LEAGUE_API_TIMEOUT,
        )
        if resp.status_code == 200:
            try:
                data = resp.json() or {}
            except ValueError:
                data = {}
    except requests.RequestException:
        data = {}

    # Only cache real responses. An empty / errored payload should not poison
    # the cache — let the next call retry the API.
    if data:
        cache.set(cache_key, data, ttl)
    return data


# ---------------------------------------------------------------------------
# Offline snapshot — used when the live API is unreachable / throttled.
# Generated by `python manage.py warm_league_cache --save-snapshot`.
# ---------------------------------------------------------------------------

def _load_snapshot() -> dict:
    if not _SNAPSHOT_PATH.exists():
        return {}
    try:
        return json.loads(_SNAPSHOT_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------

def league_info() -> dict:
    """League metadata (name, country, badge, description, website)."""
    payload = _get_json(
        "lookupleague.php",
        {"id": settings.LEAGUE_ID},
        ttl=60 * 60 * 24,
    )
    leagues = (payload or {}).get("leagues") or []
    if not leagues:
        snap = _load_snapshot().get("info") or {}
        if snap:
            return snap
        return {
            "name": settings.LEAGUE_NAME,
            "country": "Italy",
            "badge": "",
            "description": "",
            "website": "",
            "season": settings.LEAGUE_SEASON,
        }
    row = leagues[0]
    return {
        "name": row.get("strLeague") or settings.LEAGUE_NAME,
        "country": row.get("strCountry") or "Italy",
        "badge": row.get("strBadge") or row.get("strLogo") or "",
        "description": (row.get("strDescriptionEN") or "").strip(),
        "website": row.get("strWebsite") or "",
        "season": settings.LEAGUE_SEASON,
    }


def league_teams() -> list[dict]:
    """All teams in the league this season (sorted alphabetically)."""
    payload = _get_json(
        "search_all_teams.php",
        {"l": settings.LEAGUE_NAME.split(" (")[0]},  # API expects league name
        ttl=60 * 60 * 24,
    )
    teams = (payload or {}).get("teams") or []
    out = []
    for t in teams:
        out.append({
            "id": t.get("idTeam"),
            "name": t.get("strTeam"),
            "stadium": t.get("strStadium") or "",
            "country": t.get("strCountry") or "",
            "badge": t.get("strBadge") or t.get("strTeamBadge") or "",
            "is_ours": str(t.get("idTeam")) == str(settings.OUR_TEAM_ID),
        })
    if not out:
        snap = _load_snapshot().get("teams") or []
        for t in snap:
            t = dict(t)
            t["is_ours"] = str(t.get("id")) == str(settings.OUR_TEAM_ID)
            out.append(t)
    out.sort(key=lambda x: x["name"] or "")
    return out


def _round_events(round_no: int) -> list[dict]:
    payload = _get_json(
        "eventsround.php",
        {"id": settings.LEAGUE_ID, "r": round_no, "s": settings.LEAGUE_SEASON},
    )
    return (payload or {}).get("events") or []


def _normalize(ev: dict) -> dict:
    """Convert raw TheSportsDB event into the shape our templates expect."""
    home_score = ev.get("intHomeScore")
    away_score = ev.get("intAwayScore")
    played = home_score is not None and away_score is not None
    try:
        home_score_int = int(home_score) if home_score is not None else None
        away_score_int = int(away_score) if away_score is not None else None
    except (TypeError, ValueError):
        home_score_int = away_score_int = None

    home = ev.get("strHomeTeam") or ""
    away = ev.get("strAwayTeam") or ""
    our_name = settings.OUR_TEAM_NAME

    if played and home_score_int is not None and away_score_int is not None:
        if home_score_int > away_score_int:
            winner = home
        elif away_score_int > home_score_int:
            winner = away
        else:
            winner = ""
    else:
        winner = ""

    we_play = our_name.lower() in (home.lower(), away.lower())
    we_won = played and winner.lower() == our_name.lower()
    we_lost = played and we_play and not we_won

    date_str = ev.get("dateEvent") or ""
    time_str = (ev.get("strTime") or "").split("+")[0]
    try:
        date_obj = _dt.date.fromisoformat(date_str) if date_str else None
    except ValueError:
        date_obj = None

    round_raw = ev.get("intRound")
    try:
        round_no = int(round_raw) if round_raw is not None else None
    except (TypeError, ValueError):
        round_no = None
    if round_no == 0:
        round_label = "Playoffs"
    elif round_no:
        round_label = f"Round {round_no}"
    else:
        round_label = ""

    return {
        "id": ev.get("idEvent"),
        "date": date_obj,
        "date_str": date_str,
        "time": time_str,
        "home": home,
        "away": away,
        "home_score": home_score_int,
        "away_score": away_score_int,
        "venue": ev.get("strVenue") or "",
        "round": round_no,
        "round_label": round_label,
        "league": ev.get("strLeague") or settings.LEAGUE_NAME,
        "season": ev.get("strSeason") or settings.LEAGUE_SEASON,
        "played": played,
        "winner": winner,
        "involves_us": we_play,
        "we_won": we_won,
        "we_lost": we_lost,
        "score_str": (
            f"{home_score_int}–{away_score_int}"
            if home_score_int is not None and away_score_int is not None else ""
        ),
    }


def _all_season_events() -> list[dict]:
    """Pull regular-season rounds + playoff bucket. Cached (6 h)."""
    cache_key = "league:all_events_v2"
    hit = cache.get(cache_key)
    if hit is not None:
        return hit

    events: list[dict] = []
    for r in range(1, settings.LEAGUE_REGULAR_SEASON_ROUNDS + 1):
        events.extend(_round_events(r))
    events.extend(_round_events(0))  # playoffs / post-season

    seen: set[str] = set()
    deduped: list[dict] = []
    for ev in events:
        ev_id = str(ev.get("idEvent") or "")
        if ev_id and ev_id in seen:
            continue
        seen.add(ev_id)
        deduped.append(ev)
    normalized = [_normalize(e) for e in deduped]

    if not normalized:
        # Fallback to snapshot — keeps the demo working when the API is
        # rate-limited or offline.
        snapshot_events = _load_snapshot().get("events") or []
        normalized = [_normalize(e) for e in snapshot_events]

    if normalized:
        cache.set(cache_key, normalized, _DEFAULT_TTL)
    return normalized


# ---------- coach-facing accessors --------------------------------------------

def upcoming_fixtures(limit: int = 20, only_ours: bool = False) -> list[dict]:
    today = _dt.date.today()
    out = [
        e for e in _all_season_events()
        if not e["played"] and e["date"] and e["date"] >= today
        and (not only_ours or e["involves_us"])
    ]
    out.sort(key=lambda e: (e["date"], e["time"] or ""))
    return out[:limit]


def recent_results(limit: int = 20, only_ours: bool = False) -> list[dict]:
    out = [
        e for e in _all_season_events()
        if e["played"] and (not only_ours or e["involves_us"])
    ]
    out.sort(key=lambda e: (e["date"] or _dt.date.min, e["time"] or ""), reverse=True)
    return out[:limit]


def our_team_schedule() -> dict:
    events = [e for e in _all_season_events() if e["involves_us"]]
    events.sort(key=lambda e: (e["date"] or _dt.date.min, e["time"] or ""))
    today = _dt.date.today()
    played = [e for e in events if e["played"]]
    upcoming = [e for e in events if not e["played"] and e["date"] and e["date"] >= today]
    wins = sum(1 for e in played if e["we_won"])
    losses = sum(1 for e in played if e["we_lost"])
    return {
        "all": events,
        "played": played,
        "upcoming": upcoming,
        "wins": wins,
        "losses": losses,
        "win_rate": round((wins / len(played)) * 100) if played else 0,
        "next_match": upcoming[0] if upcoming else None,
        "last_match": played[-1] if played else None,
    }


# ---------- standings ----------------------------------------------------------

def league_standings() -> list[dict]:
    """Compute standings from regular-season events (rounds 1..N).

    Italian SuperLega scoring (simplified, like FIVB):
      - 3-0 / 3-1 win: 3 pts winner, 0 pts loser
      - 3-2 win: 2 pts winner, 1 pt loser
    """
    cache_key = "league:standings_v2"
    hit = cache.get(cache_key)
    if hit is not None:
        return hit

    table: dict[str, dict] = {}

    def row(name: str) -> dict:
        if name not in table:
            table[name] = {
                "team": name,
                "played": 0,
                "wins": 0,
                "losses": 0,
                "sets_won": 0,
                "sets_lost": 0,
                "points": 0,
                "is_ours": name.lower() == settings.OUR_TEAM_NAME.lower(),
            }
        return table[name]

    # Use the unified _all_season_events list — it includes snapshot fallback
    for ev in _all_season_events():
        if (ev["round"] is None or ev["round"] == 0) or not ev["played"]:
            continue
        if ev["home_score"] is None or ev["away_score"] is None:
            continue
        home = row(ev["home"])
        away = row(ev["away"])
        home["played"] += 1
        away["played"] += 1
        home["sets_won"] += ev["home_score"]
        home["sets_lost"] += ev["away_score"]
        away["sets_won"] += ev["away_score"]
        away["sets_lost"] += ev["home_score"]
        if ev["home_score"] > ev["away_score"]:
            winner, loser = home, away
        else:
            winner, loser = away, home
        winner["wins"] += 1
        loser["losses"] += 1
        if max(ev["home_score"], ev["away_score"]) == 3 and min(ev["home_score"], ev["away_score"]) == 2:
            winner["points"] += 2
            loser["points"] += 1
        else:
            winner["points"] += 3

    standings = list(table.values())
    for r in standings:
        r["set_diff"] = r["sets_won"] - r["sets_lost"]
    standings.sort(key=lambda r: (-r["points"], -r["set_diff"], -r["wins"], r["team"]))
    for i, r in enumerate(standings, start=1):
        r["rank"] = i

    if standings:
        cache.set(cache_key, standings, _DEFAULT_TTL)
    return standings


def our_team_form(limit: int = 5) -> list[str]:
    """Last <limit> results for our team as ['W', 'W', 'L', ...]."""
    played = [e for e in _all_season_events() if e["played"] and e["involves_us"]]
    played.sort(key=lambda e: (e["date"] or _dt.date.min, e["time"] or ""), reverse=True)
    out = []
    for e in played[:limit]:
        out.append("W" if e["we_won"] else "L")
    return list(reversed(out))


def upcoming_for_dashboard(limit: int = 3) -> list[dict]:
    return upcoming_fixtures(limit=limit, only_ours=True)
